name: slackpack
dependencies:
- _nb_ext_conf=0.3.0=py27_0
- alabaster=0.7.9=py27_0
- anaconda-client=1.5.3=py27_0
- appnope=0.1.0=py27_0
- babel=2.3.4=py27_0
- backports=1.0=py27_0
- backports_abc=0.4=py27_0
- boto=2.43.0=py27_0
- bz2file=0.98=py27_0
- cffi=1.8.3=py27_0
- characteristic=14.3.0=py27_0
- clyent=1.2.2=py27_0
- configparser=3.5.0=py27_0
- constantly=15.1.0=py27_0
- cryptography=1.5.3=py27_0
- cssselect=0.9.1=py27_0
- cycler=0.10.0=py27_0
- decorator=4.0.10=py27_0
- docutils=0.12=py27_2
- entrypoints=0.2.2=py27_0
- enum34=1.1.6=py27_0
- freetype=2.5.5=1
- functools32=3.2.3.2=py27_0
- futures=3.0.5=py27_0
- gensim=0.12.4=np111py27_0
- get_terminal_size=1.0.0=py27_0
- icu=54.1=0
- idna=2.0=py27_0
- imagesize=0.7.1=py27_0
- incremental=16.10.1=py27_0
- ipaddress=1.0.14=py27_0
- ipykernel=4.5.0=py27_0
- ipyparallel=5.2.0=py27_0
- ipython=5.1.0=py27_1
- ipython_genutils=0.1.0=py27_0
- ipywidgets=5.2.2=py27_0
- jinja2=2.8=py27_1
- jsonschema=2.5.1=py27_0
- jupyter=1.0.0=py27_3
- jupyter_client=4.4.0=py27_0
- jupyter_console=5.0.0=py27_0
- jupyter_core=4.2.0=py27_0
- libpng=1.6.22=0
- libxml2=2.9.2=0
- libxslt=1.1.28=2
- lxml=3.4.4=py27_0
- markupsafe=0.23=py27_2
- matplotlib=1.5.3=np111py27_1
- mistune=0.7.3=py27_1
- mkl=11.3.3=0
- nb_anacondacloud=1.2.0=py27_0
- nb_conda=2.0.0=py27_0
- nb_conda_kernels=2.0.0=py27_0
- nbconvert=4.2.0=py27_0
- nbformat=4.1.0=py27_0
- nbpresent=3.0.2=py27_0
- nltk=3.2.1=py27_0
- nose=1.3.7=py27_1
- notebook=4.2.3=py27_0
- numpy=1.11.2=py27_0
- openssl=1.0.2j=0
- pandas=0.19.1=np111py27_0
- path.py=8.2.1=py27_0
- pathlib2=2.1.0=py27_0
- pexpect=4.0.1=py27_0
- pickleshare=0.7.4=py27_0
- pip=9.0.1=py27_0
- prompt_toolkit=1.0.8=py27_0
- ptyprocess=0.5.1=py27_0
- pyasn1=0.1.9=py27_0
- pyasn1-modules=0.0.8=py27_0
- pycparser=2.14=py27_1
- pygments=2.1.3=py27_0
- pyopenssl=0.15.1=py27_2
- pyparsing=2.1.4=py27_0
- pyqt=5.6.0=py27_0
- python=2.7.12=1
- python-dateutil=2.5.3=py27_0
- pytz=2016.7=py27_0
- pyyaml=3.12=py27_0
- pyzmq=16.0.0=py27_0
- qt=5.6.0=0
- qtconsole=4.2.1=py27_1
- queuelib=1.2.2=py27_0
- readline=6.2=2
- requests=2.11.1=py27_0
- scipy=0.18.1=np111py27_0
- scrapy=1.0.3=py27_0
- seaborn=0.7.1=py27_0
- setuptools=27.2.0=py27_0
- simplegeneric=0.8.1=py27_1
- singledispatch=3.4.0.3=py27_0
- sip=4.18=py27_0
- six=1.10.0=py27_0
- smart_open=1.3.5=py27_0
- snowballstemmer=1.2.1=py27_0
- sphinx=1.4.8=py27_0
- sqlite=3.13.0=0
- ssl_match_hostname=3.4.0.2=py27_1
- terminado=0.6=py27_0
- tk=8.5.18=0
- tornado=4.4.2=py27_0
- traitlets=4.3.1=py27_0
- twisted=15.4.0=py27_0
- w3lib=1.12.0=py27_0
- wcwidth=0.1.7=py27_0
- wheel=0.29.0=py27_0
- widgetsnbextension=1.2.6=py27_0
- yaml=0.1.6=0
- zlib=1.2.8=3
- zope=1.0=py27_0
- zope.interface=4.3.2=py27_0
- pip:
  - attrs==16.2.0
  - backports-abc==0.4
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.4.0.2
  - certifi==2016.9.26
  - ipython-genutils==0.1.0
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.2.0
  - nb-anacondacloud==1.2.0
  - nb-conda==2.0.0
  - nb-conda-kernels==2.0.0
  - prompt-toolkit==1.0.8
  - service-identity==16.0.0
  - slackclient==1.0.2
  - smart-open==1.3.5
  - testpath==0.3
  - websocket-client==0.37.0
  - wordcloud==1.2.1

